rawdir: /Users/brainsimulation/Desktop/nmdare-processing/bids

outdir: /Users/brainsimulation/Desktop/nmdare-processing/results

resourcedir: /Users/brainsimulation/Desktop/nmdare-processing/resources

workflowdir: /Users/brainsimulation/Desktop/nmdare-processing/workflow


containers:
  ciftify: docker://tigrlab/fmriprep_ciftify:v1.3.2-2.3.3
  wb_command: docker://khanlab/connectome-workbench:latest