rawdir: /tmp/lima/bids

outdir: /tmp/lima/results

resourcedir: /tmp/lima/resources

workflowdir: /tmp/lima/workflow

containers:
  ciftify: docker://tigrlab/fmriprep_ciftify:v1.3.2-2.3.3
  wb_command: docker://khanlab/connectome-workbench:latest