datadir: /data/cephfs-1/work/groups/ritter/users/dada15_c/NMDARE/bids
rootdir: /data/cephfs-1/work/groups/ritter/users/dada15_c/NMDARE/nmdare-processing

containers:
  fmriprep: docker://nipreps/fmriprep:latest
  xcp_d: docker://pennlinc/xcp_d:latest