rawdir: /Users/brainsimulation/Desktop/nmdare-processing/bids

outdir: /Users/brainsimulation/Desktop/nmdare-processing/results

resourcedir: /Users/brainsimulation/Desktop/nmdare-processing/resources

workflowdir: /Users/brainsimulation/Desktop/nmdare-processing/workflow