datadir: /Volumes/KINGSTON/bids-complete
rootdir: /Users/leonmartin_bih/projects/NMDARE/nmdare-processing

containers:
  fmriprep: docker://nipreps/fmriprep:latest
  ciftify: docker://tigrlab/fmriprep_ciftify:v1.3.2-2.3.3
  wb_command: docker://khanlab/connectome-workbench:latest