datadir: /data/cephfs-1/work/groups/ritter/users/dada15_c/NMDARE/bids
rootdir: /data/cephfs-1/work/groups/ritter/users/dada15_c/NMDARE/nmdare-processing
# datadir: /Users/brainsimulation/Desktop/NMDARE/bids
# rootdir: /Users/brainsimulation/Desktop/NMDARE/nmdare-processing

containers:
  xcp_d: /data/cephfs-1/work/groups/ritter/users/dada15_c/NMDARE/nmdare-processing/.snakemake/singularity/xcpd.sif